### PR TITLE
Renew Key on KeyPermanentlyInvalidatedException

### LINKED ISSUE #24: KeyPermanentlyInvalidatedException on encrypt()
Hey,

I'm using RxFingerprint (1.2.2) encryption / decryption capabilities and I'm currently struggling with the case where key is invalidated. Here is the flow of what I'm doing :

1) Launch the activity => Ask user for some data => Encrypt that data => Save the encrypted data
2) Remove the fingerprint used for the previous encryption, then add a new one
3) Re-launch the activity => Decrypt the data => KeyPermanentlyInvalidatedException (that's fair) => Erase the encrypted data
4) Re-ask user for some data => Re-encrypt that data => KeyPermanentlyInvalidatedException (that does not seems right ?)

So it seems that I can't **re**-use encryption at all after a KeyPermanentlyInvalidatedException. Am I missing something and if not what could be the cause of this result ?

### PR DESCRIPTION
**Pull request by Mauin**
Resolves #24 

This will delete and renew the key in the Keystore when calling `RxFingerprint.encrypt(...)` when the  keys were invalidated.

### CODE REVIEW

File: rxfingerprint/src/main/java/com/mtramin/rxfingerprint/CryptoProvider.java [hunk 1]
```diff
@@ -94,6 +102,21 @@ Cipher initDecryptionCipher(byte[] iv) throws CertificateException, NoSuchAlgori
         return cipher;
     }
 
+	private Cipher cipherForEncryption() throws NoSuchAlgorithmException, NoSuchPaddingException, CertificateException, UnrecoverableKeyException, KeyStoreException, NoSuchProviderException, InvalidAlgorithmParameterException, IOException, InvalidKeyException {
```
Comment (dmitry-zaitsev) [inline rxfingerprint/src/main/java/com/mtramin/rxfingerprint/CryptoProvider.java]: Indentation seem to be wrong
